; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:WT32SC01PLUS]
platform = https://github.com/pioarduino/platform-espressif32/
board = WT32SC01PLUS_N16R2
framework = arduino

; Upload configuration
upload_speed = 921600
monitor_speed = 115200

; Build flags
build_flags =
    -std=gnu++20
    -DCORE_DEBUG_LEVEL=0
    ; -mfix-esp32-psram-cache-issue
    ; -DLGFX_USE_V1
    ; -DCONFIG_SPIRAM_CACHE_WORKAROUND
    ; -DCONFIG_SPIRAM_USE_MALLOC
    ; -Os
    ; -DCONFIG_FREERTOS_HZ=100
    ; -DCONFIG_LOG_DEFAULT_LEVEL=3
    ; TCP/IP Network Configuration (optimized for audio streaming)
    -DCONFIG_LWIP_MAX_ACTIVE_TCP=512
    -DCONFIG_LWIP_MAX_LISTENING_TCP=512
    -DCONFIG_LWIP_TCP_MSS=1436
    -DCONFIG_LWIP_TCP_SND_BUF_DEFAULT=16384
    -DCONFIG_LWIP_TCP_WND_DEFAULT=65535
    -DCONFIG_LWIP_TCP_RECVMBOX_SIZE=6
    -DCONFIG_LWIP_TCPIP_RECVMBOX_SIZE=32
    -DCONFIG_LWIP_SO_RCVBUF=1
    -DCONFIG_LWIP_TCP_SYNMAXRTX=6
    -DCONFIG_LWIP_TCP_MAXRTX=12

; Library dependencies
lib_deps =
    https://github.com/lovyan03/LovyanGFX#develop
    https://github.com/schreibfaul1/ESP32-audioI2S.git
    bblanchon/ArduinoJson@7.0.4

; Filesystem
board_build.filesystem = littlefs
