; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Common settings for all environments
[env]
platform = https://github.com/pioarduino/platform-espressif32/
board = WT32SC01PLUS_N16R2
framework = arduino, espidf
monitor_speed = 115200

; Build flags
build_flags =
    -std=gnu++20
    -D CORE_DEBUG_LEVEL=3
    -D AUDIOTASK_CORE=0
    -Wall
    -Wextra
    -Wno-cpp                                 ; Disable #warning directive warnings
    -Wno-format                              ; Disable all format string warnings
    -Wno-unused-function
    -Wno-missing-field-initializers
    -fdiagnostics-color=always
    -Wno-error=class-memaccess
    ; -DCONFIG_SPIRAM_USE_MALLOC
    ; -DCONFIG_SPIRAM_CACHE_WORKAROUND
    ; ; Increase TCP receive buffer for smoother streaming
    ; -DCONFIG_LWIP_MAX_ACTIVE_TCP=32
    ; -DCONFIG_LWIP_MAX_LISTENING_TCP=64
    ; -DCONFIG_LWIP_TCP_HIGH_SPEED_RETRANSMISSION=y
    ; -DCONFIG_LWIP_TCP_MAXRTX=12
    ; -DCONFIG_LWIP_TCP_SYNMAXRTX=6
    ; -DCONFIG_LWIP_TCP_MSS=1436
    ; -DCONFIG_LWIP_TCP_TMR_INTERVAL=200
    ; -DCONFIG_LWIP_TCP_MSL=1600
    ; -DCONFIG_LWIP_TCP_FIN_WAIT_TIMEOUT=1000
    ; -DCONFIG_LWIP_TCP_SND_BUF_DEFAULT=32768
    ; -DCONFIG_LWIP_TCP_WND_DEFAULT=32768
    ; -DCONFIG_LWIP_TCP_RECVMBOX_SIZE=32
    ; -DCONFIG_LWIP_TCP_ACCEPTMBOX_SIZE=12
    ; -DCONFIG_LWIP_TCP_QUEUE_OOSEQ=y
    ; -DCONFIG_LWIP_TCP_OOSEQ_TIMEOUT=4
    ; -DCONFIG_LWIP_TCP_OOSEQ_MAX_PBUFS=12
    ; -DCONFIG_LWIP_TCP_SACK_OUT=y
    ; -DCONFIG_LWIP_TCP_OVERSIZE_MSS=y


board_build.embed_txtfiles =
    managed_components/espressif__esp_insights/server_certs/https_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt

; Library dependencies
lib_deps =
    https://github.com/lovyan03/LovyanGFX#develop
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.4.4
    bblanchon/ArduinoJson@7.0.4

; Filesystem
board_build.filesystem = littlefs

board_build.partitions = partition_16MB_ota_spiffs.csv

; USB Upload Environment (default)
[env:usb]
upload_speed = 921600

; OTA Upload Environment
[env:ota]
upload_protocol = espota
upload_port = retrodio.local
upload_flags =
    --port=3232
